name: Create frontend docker image

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKER_REGISTRY_USERNAME:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true
      HOOK_TOKEN:
        required: true

concurrency:
  group: build-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    environment: registry

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to registry
        uses: docker/login-action@v4
        with:
          registry: registry.keireira.com
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build
        run: |
          docker build --file frontend/Dockerfile \
            --tag "registry.keireira.com/sharkie-fe:latest" \
            frontend

      - name: Publish
        run: docker push "registry.keireira.com/sharkie-fe:latest"

      - name: Registry cleanup
        run: |
          curl -sf -H 'X-Webhook-Token: ${{ secrets.HOOK_TOKEN }}' \
            https://hooks.keireira.com/registry-cleanup
